### PR TITLE
[bug] Fixed compilation error caused by #7047

### PR DESCRIPTION
**Pull request by PGZXB**
Issue: #7047

### CODE REVIEW

**Review by lin-hitonami — APPROVED** [review]
LGTM

**Comment by lin-hitonami** [comment]
Force merging to save the master
