### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by yuqingyang888** [taichi-dev/taichi#347]
[100%] Linking CXX shared library libtaichi_core.so
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/taichi_core.dir/build.make:1482: recipe for target 'libtaichi_core.so' failed
make[2]: *** [libtaichi_core.so] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/taichi_core.dir/all' failed
make[1]: *** [CMakeFiles/taichi_core.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
  Error: Build failed.
  Error: installation failed.

System:Ubuntu 16.04
I try to use python install.py to install. However, in the last step, error occurs.

**Comment by yuanming-hu** [comment]
Hi @yuqingyang888 

Thanks for reporting. Are you planning to develop the taichi compiler, or just want to try it out? For the latter case using pip to install will be way easier.

**Comment by FrankHB** [comment]
Not tried yet, but isn't this way necessary to work with Python 3.8?

**Comment by yuqingyang888** [comment]
I've already install the pip version and I'm trying the example in taichi-mpm. However, error occurs as below, and is it the only way to use this example?

Traceback (most recent call last):
  File "banana.py", line 8, in <module>
    mpm = tc.dynamics.MPM(
AttributeError: module 'taichi' has no attribute 'dynamics'

As to join this project, it would be a great honor. But I really don't have much comiler knowledge~

**Comment by Shatom** [comment]
> [100%] Linking CXX shared library libtaichi_core.so /usr/bin/ld: /usr/local/lib/libpython3.6m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC /usr/local/lib/libpython3.6m.a: error adding symbols: Bad value collect2: error: ld returned 1 exit status CMakeFiles/taichi_core.dir/build.make:1482: recipe for target 'libtaichi_core.so' failed make[2]: *** [libtaichi_core.so] Error 1 CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/taichi_core.dir/all' failed make[1]: *** [CMakeFiles/taichi_core.dir/all] Error 2 Makefile:83: recipe for target 'all' failed make: *** [all] Error 2 Error: Build failed. Error: installation failed.
> 
> System:Ubuntu 16.04 I try to use python install.py to install. However, in the last step, error occurs.

Hi, yuqing. Have you fixed this error? I have met the same one, could you help?
