### PR TITLE
[bug] [refactor] Fix error when ti.init() not called by deprecating Expr.layout_materialized

### LINKED ISSUE #1335: type object 'Expr' has no attribute 'layout_materialized'
**Describe the bug**
The autodiff_minimization.py/autodiff_regression.py examples are not working in 0.6.13 version but working in 0.6.12

**Log/Screenshots**
```
[Taichi] mode=release
[Taichi] version 0.6.13, llvm 10.0.0, commit e8d87357, python 3.7.6
Traceback (most recent call last):
  File "autodiff_minimization.py", line 18, in <module>
    x[i] = random.random()
  File "/home/vkurenkov/.anaconda3/lib/python3.7/site-packages/taichi/lang/util.py", line 212, in wrapped
    return func(*args, **kwargs)
  File "/home/vkurenkov/.anaconda3/lib/python3.7/site-packages/taichi/lang/expr.py", line 39, in __setitem__
    impl.get_runtime().try_materialize()
  File "/home/vkurenkov/.anaconda3/lib/python3.7/site-packages/taichi/lang/impl.py", line 166, in try_materialize
    if not Expr.layout_materialized:
AttributeError: type object 'Expr' has no attribute 'layout_materialized'
```

**To Reproduce**
```
# Install target version
pip install taichi==0.6.13

# Pull the example
git clone https://github.com/taichi-dev/taichi.git
cd taichi/examples/

# Run the example
python autodiff_minimization.py
```

### PR DESCRIPTION
**Pull request by archibate**
Related issue = close #1335

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----
I'm not sure why @yuanming-hu use `Expr.layout_materialized` instead of simply `ti.get_runtime().materialized` at the first place, maybe it was due to `get_runtime()` not done at that moment?

### CODE REVIEW

File: python/taichi/lang/expr.py [hunk 1]
```diff
@@ -114,7 +114,7 @@ def fill(self, val):
         from .meta import fill_tensor
         fill_tensor(self, val)
 
-    @deprecated('tensor.parent()', 'tensor.snode().parent()')
+    #@deprecated('tensor.parent()', 'tensor.snode().parent()')
```
Comment (yuanming-hu) [inline python/taichi/lang/expr.py:117]: So we no longer deprecate this?

File: tests/python/test_000_runtime.py [hunk 2]
```diff
@@ -0,0 +1,50 @@
+import taichi as ti
+
+
+# The first test to run, ever:
+def test_000_without_init():
```
Comment (yuanming-hu) [inline tests/python/test_000_runtime.py:5]: What does `000` mean here and in the file name?

File: python/taichi/lang/impl.py [hunk 3]
```diff
@@ -279,8 +272,13 @@ def var(dt, shape=None, offset=None, needs_grad=False):
...
             ) == False, f'The shape cannot be None when offset is being set'
 
-    assert not get_runtime(
-    ).materialized, 'No new variables can be declared after kernel invocations or Python-scope tensor accesses.'
+    if get_runtime().materialized:
+        raise RuntimeError(
+            "No new variables can be declared after materialization, i.e. kernel invocations "
+            "or Python-scope tensor accesses. I.e. only after all the data layouts are defined, "
+            "we can initialize our data and run computation. Try append ti.init() or ti.reset() "
+            "right after 'import taichi as ti' if you are using Jupyter notebook."
```
Comment (yuanming-hu) [inline python/taichi/lang/impl.py:280]:
```suggestion
            "No new variables can be declared after materialization, i.e. kernel invocations "
            "or Python-scope tensor accesses. I.e., data layouts must be specified before "
            "any computation. Try appending ti.init() or ti.reset() "
            "right after 'import taichi as ti' if you are using Jupyter notebook."
```

File: python/taichi/lang/expr.py (hunk 1 above)
Comment (archibate) [reply python/taichi/lang/expr.py:117]: Yes, since `tensor.parent()` returns a `tensor` while `tensor.snode().parent()` return a snode, it seems this is irreplaceable and many test is using this..

File: tests/python/test_000_runtime.py (hunk 2 above)
Comment (archibate) [reply tests/python/test_000_runtime.py:5]: Seems `pytest` will starts from the lowest character order, so I use `000` to make `test_000_without_init` starts at the very first time when `ti.init()` has never been called in `@ti.all_archs`, to test if Taichi is functional even without `ti.init()`.

Comment (yuanming-hu) [reply tests/python/test_000_runtime.py]: Interesting - maybe we should simply let `ti.reset` clear everything, as if no `ti.init()` has been called? This will make the system more testable.

Comment (archibate) [reply tests/python/test_000_runtime.py]: > `ti.reset()`

I want to test if non of `ti.reset` or `ti.init` is called is working.
So, I'm creating a sandbox Taichi by creating a `taichi_temp_test.py` for test.

Btw, we may add a `ti.reset()` to taichi startup script to make your test method work? Not sure if this can crash doc-bots & make startup slower.

File: tests/python/test_runtime.py [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+assert x[1, 2] == 4
+'''
+    filename = make_temp_file()
+    with open(filename, 'w') as f:
+        f.write(content)
+    assert os.system(f'{sys.executable} {filename}') == 0
+
+
+@ti.all_archs
+@ti.all_archs
```
Comment (k-ye) [inline tests/python/test_runtime.py:27]: duplicate?
```suggestion
```
