### ISSUE TITLE
excepthook=True and ti.enable_excepthook() broken - breaking change? [v0.8.7]

### ISSUE THREAD

**Issue by whorfin** [taichi-dev/taichi#3775]
**Describe the bug**
calling `ti.init()` with `excepthook=True` or calling `ti.enable_excepthook()` now fail with version 0.8.7.
It appears that this was introduced by 36ca6f1f14c58f6319aeac6c2053c863fe99f7ff via #3671 
Discussion in the commit indicates this might have been intentional (?) but the documentation still references it and so does code in the release.  If this is indeed going away, it would be helpful if it were called out as a breaking change.

**To Reproduce**

In the taichi source directory, run:
```
$ python3 misc/demo_excepthook.py # this code still present in master
[Taichi] version 0.8.7, llvm 10.0.0, commit 88d81df6, win, python 3.9.7
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "...\taichi\misc\demo_excepthook.
py", line 4, in <module>
    ti.enable_excepthook()
  File "C:\Users\whorfin\AppData\Local\Programs\Python\Python39\lib\site-packages\taichi\__init__.
py", line 35, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
AttributeError: module 'taichi' has no attribute 'enable_excepthook'
```
Alternatively, this minimal taichi program will trigger the same error:
```
ti.init(excepthook=True)
```

For example:
```
$ python3 -m taichi repl
[Taichi] version 0.8.7, llvm 10.0.0, commit 88d81df6, win, python 3.9.7

*******************************************
**      Taichi Programming Language      **
*******************************************

Docs:   https://docs.taichi.graphics/
GitHub: https://github.com/taichi-dev/taichi/
Forum:  https://forum.taichi.graphics/

Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.28.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: ti.init(excepthook=True)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Programs\Python\Python39\lib\site-packages\taichi\main.py in <module>
----> 1 ti.init(excepthook=True)

~\AppData\Local\Programs\Python\Python39\lib\site-packages\taichi\lang\__init__.py in init(arch, d
efault_fp, default_ip, _test_mode, enable_fallback, **kwargs)
    634         if spec_cfg.excepthook:
    635             # TODO(#1405): add a way to restore old excepthook
--> 636             ti.enable_excepthook()
    637
    638     # select arch (backend):

~\AppData\Local\Programs\Python\Python39\lib\site-packages\taichi\__init__.py in __getattr__(attr)
     33             exec(f'{attr} = {deprecated_names[attr]}')
     34             return locals()[attr]
---> 35         raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
     36
     37

AttributeError: module 'taichi' has no attribute 'enable_excepthook'
```

**Comment by ailzhang** [comment]
Hey @whorfin, thanks for reporting the issue! Yea the removal was indeed intended but we could have done it better by deprecating it first. So sorry for the inconvenience!

Some context: This exceptionhook was introduced to simplify/prettify the traceback when exception is thrown. But we (by we I meant @lin-hitonami  :P ) have refactor the frontend ast generator so hiding python stack trace is no longer needed/preferred. We plan to just expose all the native python traceback to users to help them locate the problem. https://github.com/taichi-dev/taichi/issues/2489

**Comment by strongoier** [comment]
Besides #2489, we should also remove all occurrences of `excepthook` (https://github.com/taichi-dev/taichi/search?q=excepthook). :-)

**Comment by strongoier** [comment]
Closed via #3902.
