### ISSUE TITLE
AttributeError: module 'taichi' has no attribute 'Vector'

### ISSUE THREAD

**Issue by onefish51** [taichi-dev/taichi#361]
I installed taichi by `python3 -m pip install taichi-nightly`
```sh
Collecting taichi-nightly
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a6/c6/16a0ee81a207a6b93ee7ee54ec4414b652c824bcc972b9605807873d87b8/taichi_nightly-0.3.20-cp37-cp37m-macosx_10_14_x86_64.whl
...
Successfully installed astor-0.8.1 pybind11-2.4.3 taichi-nightly-0.3.20
```
but when I run ` import taichi as ti`
```sh
Traceback (most recent call last):
  File "taichi.py", line 3, in <module>
    import taichi as ti
  File "/Users/admin/code/python/python_base/taichi.py", line 14, in <module>
    x = ti.Vector(2, dt=ti.f32, shape=n_particles)  # position
AttributeError: module 'taichi' has no attribute 'Vector'
```

**Comment by yuanming-hu** [comment]
You installation is OK but please change the 99-line simulator file name to something other than taichi.py

**Comment by onefish51** [comment]
The error is fixed ,but there's something wrong thrown out ! 
I run it on macOS Catalina , Does it support ?

**Comment by pavilion2t** [comment]
@onefish51   it's better to use 10.14, see here  https://github.com/yuanming-hu/taichi/issues/340#issuecomment-571005163

**Comment by onefish51** [comment]
> It would be great to have Catalina supported. Our project crashes on OS X 10.15 but works well on <= 10.14. We need a CI that supports Catalina to reproduce and fix this, as none of us wants to upgrade our own Mac to 10.15, which is known to have quite a few compatibility issues. A lot of users are asking us to fix that. Thanks so much!

I found it ! A bad news !
I run it on Ubuntu ,but I visit it by Terminal, NO GUI !

**Comment by yuanming-hu** [comment]
Thanks for trying Taichi. You may want to try `ssh -XY` which enables X11 forwarding.
