### ISSUE TITLE
CUDA 10.2 problem: invalid argument while calling device_get_attribute (cuDeviceGetAttribute)

### ISSUE THREAD

**Issue by Hecate2** [taichi-dev/taichi#3917]
**Describe the bug**
Failed to execute `ti.init(ti.cuda)` on Windows with taichi==0.8.7 and 0.8.8, but successful with taichi==0.8.6. 

**To Reproduce**
```py
import taichi as ti
ti.init(ti.cuda)
```
Environment: Windows 10, CUDA 10.2, Python 3.8. 

**Log/Screenshots**
With taichi==0.8.7,
```
[Taichi] version 0.8.7, llvm 10.0.0, commit 88d81df6, win, python 3.8.10
[Taichi] Starting on arch=cuda
[E 12/30/21 18:15:46.847 9316] [taichi/backends/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<int *,unsigned int,void *>::operator ()@87] CUDA Error CUDA_ERROR_INVALID_VALUE: invalid argument while calling device_get_attribute (cuDeviceGetAttribute)


Traceback (most recent call last):
  File "C:/Users/RhantolkYtriHistoria/tmp/taichi/helloworld_taichi.py", line 3, in <module>
    ti.init(ti.cuda)
  File "C:\Program Files\Python38\lib\site-packages\taichi\lang\__init__.py", line 663, in init
    impl.get_runtime().create_program()
  File "C:\Program Files\Python38\lib\site-packages\taichi\lang\impl.py", line 331, in create_program
    self.prog = _ti_core.Program()
RuntimeError: [taichi/backends/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<int *,unsigned int,void *>::operator ()@87] CUDA Error CUDA_ERROR_INVALID_VALUE: invalid argument while calling device_get_attribute (cuDeviceGetAttribute)
```
With taichi==0.8.8, (essentialy the same problem)
```
[Taichi] version 0.8.8, llvm 10.0.0, commit 7bae9c77, win, python 3.8.10
[Taichi] Starting on arch=cuda
[E 12/30/21 18:19:46.894 20388] [taichi/backends/cuda/cuda_driver.h:operator()@87] CUDA Error CUDA_ERROR_INVALID_VALUE: invalid argument while calling device_get_attribute (cuDeviceGetAttribute)


Traceback (most recent call last):
  File "C:/Users/RhantolkYtriHistoria/tmp/taichi/helloworld_taichi.py", line 3, in <module>
    ti.init(ti.cuda)
  File "C:\Program Files\Python38\lib\site-packages\taichi\lang\__init__.py", line 645, in init
    impl.get_runtime().create_program()
  File "C:\Program Files\Python38\lib\site-packages\taichi\lang\impl.py", line 301, in create_program
    self.prog = _ti_core.Program()
RuntimeError: [taichi/backends/cuda/cuda_driver.h:operator()@87] CUDA Error CUDA_ERROR_INVALID_VALUE: invalid argument while calling device_get_attribute (cuDeviceGetAttribute)
```
But everything works well with taichi==0.8.6.

ti diagnose:
```
Rhantolk@HISTORIA C:\Users\RhantolkYtriHistoria
# ti diagnose
[Taichi] version 0.8.8, llvm 10.0.0, commit 7bae9c77, win, python 3.8.10

*******************************************
**      Taichi Programming Language      **
*******************************************

Docs:   https://docs.taichi.graphics/
GitHub: https://github.com/taichi-dev/taichi/
Forum:  https://forum.taichi.graphics/

Taichi system diagnose:

python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
system: win32
executable: c:\program files\python38\python.exe
platform: Windows-10-10.0.18362-SP0
architecture: 64bit WindowsPE
uname: uname_result(system='Windows', node='Historia', release='10', version='10.0.18362', machine='AMD64', processor='AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD')
locale: zh_CN.cp936
PATH: C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu\ConEmu;C:\GAMS\win64\28.2;C:\GAMS\win64\28.2\gbin;C:\Program Files\Python38\Scripts\;C:\Program Files\Python38\;C:\Users\RhantolkYtriHistoria\AppData\Roaming\Python\Python37\Scripts;C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\NetSarang\Xlpd 6\;C:\Program Files (x86)\NetSarang\Xftp 6\;C:\Program Files (x86)\NetSarang\Xshell 6\;C:\Program Files (x86)\NetSarang\Xmanager 6\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Users\RhantolkYtriHistoria\AppData\Roaming\Python\Python36\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\ConEmu;C:\MinGW\bin;C:\Program Files\Java\jdk1.8.0_251\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Calibre2\;C:\Users\RhantolkYtriHistoria\Softwares\rclone-v1.54.0-windows-amd64;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Users\RhantolkYtriHistoria\AppData\Local\Microsoft\WindowsApps;C:\texlive\2020\bin\win32;C:\Users\RhantolkYtriHistoria\AppData\Local\Programs\Fiddler;C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\bin;C:\Users\RhantolkYtriHistoria\.dotnet\tools;C:\Users\RhantolkYtriHistoria\AppData\Roaming\npm;C:\Program Files\Python38\Lib\site-packages\taichi\_lib
PYTHONPATH: ['C:\\Program Files\\Python38\\Scripts\\ti.exe', 'c:\\program files\\python38\\python38.zip', 'c:\\program files\\python38\\DLLs', 'c:\\program files\\python38\\lib', 'c:\\program files\\python38', 'C:\\Users\\RhantolkYtriHistoria\\AppData\\Roaming\\Python\\Python38\\site-packages', 'c:\\program files\\python38\\lib\\site-packages', 'c:\\program files\\python38\\lib\\site-packages\\docloud-1.0.375-py3.8.egg']


`lsb_release` not available: [WinError 2] 系统找不到指定的文件。


import: <module 'taichi' from 'c:\\program files\\python38\\lib\\site-packages\\taichi\\__init__.py'>

cc: False
cpu: True
metal: False
opengl: True
cuda: True
vulkan: True

`glewinfo` not available: [WinError 2] 系统找不到指定的文件。

Thu Dec 30 18:23:07 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 442.31       Driver Version: 442.31       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070   WDDM  | 00000000:06:00.0  On |                  N/A |
| N/A   45C    P0    24W /  N/A |   1535MiB /  8192MiB |      7%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1268    C+G   Insufficient Permissions                   N/A      |
|    0      2128    C+G   ...ogram Files\Mozilla Firefox\firefox.exe N/A      |
|    0      2264    C+G   ...t_cw5n1h2txyewy\ShellExperienceHost.exe N/A      |
|    0      3076    C+G   ...ogram Files\Mozilla Firefox\firefox.exe N/A      |
|    0      6284    C+G   C:\Windows\explorer.exe                    N/A      |
|    0      7300    C+G   ...dows.Cortana_cw5n1h2txyewy\SearchUI.exe N/A      |
|    0      9392    C+G   ...mmersiveControlPanel\SystemSettings.exe N/A      |
|    0     10264    C+G   ...iles (x86)\Tencent\WeChat\wechatweb.exe N/A      |
|    0     10392    C+G   ...DIA GeForce Experience\NVIDIA Share.exe N/A      |
|    0     10548    C+G   ...a\Roaming\Telegram Desktop\Telegram.exe N/A      |
|    0     11252    C+G   ...\Local\Discord\app-1.0.9003\Discord.exe N/A      |
|    0     11388    C+G   ...iles (x86)\Tencent\WeChat\WeChatApp.exe N/A      |
|    0     11856    C+G   ...ogram Files\Mozilla Firefox\firefox.exe N/A      |
|    0     12728    C+G   ...ogram Files\Mozilla Firefox\firefox.exe N/A      |
|    0     13108    C+G   ...ogram Files\Mozilla Firefox\firefox.exe N/A      |
|    0     15212    C+G   ...ogram Files\Mozilla Firefox\firefox.exe N/A      |
|    0     16028    C+G   ...ogram Files\Mozilla Firefox\firefox.exe N/A      |
|    0     16728    C+G   ...hell.Experiences.TextInput.InputApp.exe N/A      |
|    0     22488    C+G   ...ogram Files\Mozilla Firefox\firefox.exe N/A      |
|    0     22668    C+G   ...ogram Files\Mozilla Firefox\firefox.exe N/A      |
+-----------------------------------------------------------------------------+

[Taichi] version 0.8.8, llvm 10.0.0, commit 7bae9c77, win, python 3.8.10

[Taichi] version 0.8.8, llvm 10.0.0, commit 7bae9c77, win, python 3.8.10
[Taichi] Starting on arch=x64

[Taichi] version 0.8.8, llvm 10.0.0, commit 7bae9c77, win, python 3.8.10
[Taichi] Starting on arch=opengl

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python38\lib\site-packages\taichi\lang\__init__.py", line 645, in init
    impl.get_runtime().create_program()
  File "c:\program files\python38\lib\site-packages\taichi\lang\impl.py", line 301, in create_program
    self.prog = _ti_core.Program()
RuntimeError: [taichi/backends/cuda/cuda_driver.h:operator()@87] CUDA Error CUDA_ERROR_INVALID_VALUE: invalid argument while calling device_get_attribute (cuDeviceGetAttribute)
Taichi CUDA test failed: Command '['c:\\program files\\python38\\python.exe', '-c', 'import taichi as ti; ti.init(arch=ti.cuda)']' returned non-zero exit status 1.
[Taichi] version 0.8.8, llvm 10.0.0, commit 7bae9c77, win, python 3.8.10

*******************************************
**      Taichi Programming Language      **
*******************************************

Docs:   https://docs.taichi.graphics/
GitHub: https://github.com/taichi-dev/taichi/
Forum:  https://forum.taichi.graphics/

Running example minimal ...
[Taichi] Starting on arch=x64
42.0
>>> Running time: 0.24s
42

Consider attaching this log when maintainers ask about system information.
>>> Running time: 5.14s
```

**Comment by Hecate2** [comment]
Based on the release dates and the commits, this may be related to https://github.com/taichi-dev/taichi/blob/7a1a1e1067a45441a10cb23a88202469556b4eb0/taichi/llvm/llvm_program.cpp#L74-L76 .

**Comment by zkyf** [comment]
same here, after changing to opengl backend, the error becomes:
```
[Taichi] Starting on arch=opengl
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    pixels = ti.var(dt=ti.f32, shape=(n * 2, n))
AttributeError: module 'taichi' has no attribute 'var'
```

**Comment by k-ye** [comment]
> same here, after changing to opengl backend, the error becomes:
> 
> ```
> [Taichi] Starting on arch=opengl
> Traceback (most recent call last):
>   File "main.py", line 8, in <module>
>     pixels = ti.var(dt=ti.f32, shape=(n * 2, n))
> AttributeError: module 'taichi' has no attribute 'var'
> ```

Hi, `ti.var` has long been deprecated. Please use `ti.field` instead, thx!

**Comment by qiao-bo** [comment]
Hi, FYI, this should be fixed in our latest 0.8.9 release. Please check again and let us know, thanks!

**Comment by Hecate2** [comment]
It works with taichi==0.8.9 on Windows with CUDA 10.2. Thank you very much!
