### ISSUE TITLE
fill() not working after upgrading to 1.6.0

### ISSUE THREAD

**Issue by zhouxian** [taichi-dev/taichi#8233]
The following code snippet doesn't work after i upgraded to 1.6.0:
```python
import taichi as ti
ti.init(ti.gpu)
particle_info = ti.types.struct(
    v_in  = ti.types.vector(3, ti.f32), # input momentum/velocity
    mu      = ti.f32,
    lam     = ti.f32,
)

particles = particle_info.field(shape=(10, 100, 100), layout=ti.Layout.SOA)


@ti.kernel
def foo(f: ti.i32):
    for I in ti.grouped(ti.ndrange(100, 100)):
        particles[f, I].fill(0)

foo(5)
```

```bash
AttributeError: '_IntermediateStruct0' object has no attribute 'fill'
```
It used to work before 1.6.0. What should i do to set elements in a struct field to zero? I can iterate over all elements in the struct, but it's too clumsy.

**Comment by lin-hitonami** [comment]
It turns out that we deprecated fuction `fill` of Struct in v1.5.0 and removed it in v1.6.0, and we forgot to mention it on the release note. We are sorry for the inconvenience.

**Comment by zhouxian** [comment]
@lin-hitonami Is there any clean way to fill all elements in a struct to be 0?

**Comment by lin-hitonami** [comment]
Sadly no. You have to set each element to zero now.
