### ISSUE TITLE
A problem found in memory recycling example in /Docs/Advanced Programming/Data oriented Class

### ISSUE THREAD

**Issue by PatternFyenman** [taichi-dev/taichi#6729]
When I ran the code provided by the memory recycling example, it throw an error to me, "**'Calc' object has no attribute 'y'**" in the code line 28: 
```python
print(a.y) # [ 5. 13. 21. 29.]
```
I have little knowledge of memory recycling, and I would greatly appreciate it if anyone explains this error or how this code achieves memory recycling. Thanks!

![memory_recycling_error](https://user-images.githubusercontent.com/82517756/203885177-ae798e0d-fcba-4ae2-b6f6-98a9ddcddb1d.png)

**Comment by ailzhang** [comment]
@PatternFyenman Thanks for reporting! This is indeed a bug in our doc introduced in #6181 . 
@neozhaoliang #6181 deleted the `y` attribute in the `Calc` class, is it intended? (If not, would you mind sending a fix? Thanks a lot!

**Comment by neozhaoliang** [comment]
@PatternFyenman Thanks for pointing out this error! This will be fixed by #6790
