### ISSUE TITLE
some error on version 0.8.6

### ISSUE THREAD

**Issue by bolin12** [taichi-dev/taichi#3625]
I encountered some ploblems:
version 0.8.6 will display a totally chaos of this script https://github.com/taichiCourse01/taichi_ray_tracing/blob/master/4_0_path_tracing.py

and also report  " 'float' object has no attribute 'ptr' " error of this
https://github.com/taichiCourse01/taichi_ray_tracing/blob/master/3_2_whitted_style_ray_tracing.py

as I switched back to earlier version 0.8.4, problems above are gone.

Are there problems related to my machine? thanks!

**Comment by strongoier** [comment]
Could you provide the complete error message? Thanks!

**Comment by bolin12** [comment]
[Taichi] version 0.8.6, llvm 10.0.0, commit d5f18ffd, linux, python 3.8.10
[Taichi] Starting on arch=cuda
Traceback (most recent call last):
  File "3_2_whitted_style_ray_tracing.py", line 242, in <module>
    render()
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 702, in wrapped
    return primal(*args, **kwargs)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 628, in __call__
    key = self.ensure_compiled(*args)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 619, in ensure_compiled
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 466, in materialize
    taichi_kernel = _ti_core.create_kernel(taichi_ast_generator,
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 461, in taichi_ast_generator
    visitor.visit(tree)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast/transformer.py", line 47, in visit
    tree = IRBuilder()(ctx, tree)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 425, in build_Module
    node.body = [build_stmt(ctx, stmt) for stmt in list(node.body)]
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 425, in <listcomp>
    node.body = [build_stmt(ctx, stmt) for stmt in list(node.body)]
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 396, in build_FunctionDef
    build_stmts(ctx, node.body)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 959, in build_stmts
    result.append(build_stmt(ctx, stmt))
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 790, in build_For
    return IRBuilder.build_struct_for(ctx, node, is_grouped=False)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 707, in build_struct_for
    node.body = build_stmts(ctx, node.body)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 959, in build_stmts
    result.append(build_stmt(ctx, stmt))
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 779, in build_For
    return IRBuilder.build_range_for(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 603, in build_range_for
    node.body = build_stmts(ctx, node.body)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 959, in build_stmts
    result.append(build_stmt(ctx, stmt))
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 459, in build_AugAssign
    node.value = build_stmt(ctx, node.value)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 307, in build_Call
    node.ptr = node.func.ptr(*args, **keywords)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 59, in decorated
    return fun.__call__(*args)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 166, in __call__
    return visitor.visit(tree, *args)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast/transformer.py", line 47, in visit
    tree = IRBuilder()(ctx, tree)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 425, in build_Module
    node.body = [build_stmt(ctx, stmt) for stmt in list(node.body)]
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 425, in <listcomp>
    node.body = [build_stmt(ctx, stmt) for stmt in list(node.body)]
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 396, in build_FunctionDef
    build_stmts(ctx, node.body)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 959, in build_stmts
    result.append(build_stmt(ctx, stmt))
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 807, in build_While
    node.body = build_stmts(ctx, node.body)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 959, in build_stmts
    result.append(build_stmt(ctx, stmt))
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 825, in build_If
    node.body = build_stmts(ctx, node.body)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 959, in build_stmts
    result.append(build_stmt(ctx, stmt))
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 828, in build_If
    node.orelse = build_stmts(ctx, node.orelse)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 959, in build_stmts
    result.append(build_stmt(ctx, stmt))
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 825, in build_If
    node.body = build_stmts(ctx, node.body)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 959, in build_stmts
    result.append(build_stmt(ctx, stmt))
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 23, in build_Assign
    node.value = build_stmt(ctx, node.value)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 307, in build_Call
    node.ptr = node.func.ptr(*args, **keywords)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 59, in decorated
    return fun.__call__(*args)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 166, in __call__
    return visitor.visit(tree, *args)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast/transformer.py", line 47, in visit
    tree = IRBuilder()(ctx, tree)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 425, in build_Module
    node.body = [build_stmt(ctx, stmt) for stmt in list(node.body)]
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 425, in <listcomp>
    node.body = [build_stmt(ctx, stmt) for stmt in list(node.body)]
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 396, in build_FunctionDef
    build_stmts(ctx, node.body)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 959, in build_stmts
    result.append(build_stmt(ctx, stmt))
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 23, in build_Assign
    node.value = build_stmt(ctx, node.value)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 289, in build_Call
    node.ptr = node.func.ptr(*args, **keywords)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 59, in decorated
    return fun.__call__(*args)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 166, in __call__
    return visitor.visit(tree, *args)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast/transformer.py", line 47, in visit
    tree = IRBuilder()(ctx, tree)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 425, in build_Module
    node.body = [build_stmt(ctx, stmt) for stmt in list(node.body)]
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 425, in <listcomp>
    node.body = [build_stmt(ctx, stmt) for stmt in list(node.body)]
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 396, in build_FunctionDef
    build_stmts(ctx, node.body)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 959, in build_stmts
    result.append(build_stmt(ctx, stmt))
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 758, in build_For
    return IRBuilder.build_static_for(
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 574, in build_static_for
    node.body = build_stmts(ctx, node.body)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 959, in build_stmts
    result.append(build_stmt(ctx, stmt))
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ast_builder_utils.py", line 16, in __call__
    return method(ctx, node)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 34, in build_Assign
    IRBuilder.build_assign_unpack(ctx, node_target, node.value.ptr,
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 58, in build_assign_unpack
    IRBuilder.build_assign_basic(ctx, target, tmp_tuple[i],
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ir_builder.py", line 86, in build_assign_basic
    var.assign(value)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/common_ops.py", line 289, in assign
    return ti.assign(self, other)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ops.py", line 128, in wrapped
    return a.element_wise_writeback_binary(imp_foo, b)
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/matrix.py", line 182, in element_wise_writeback_binary
    entries = [[foo(self(i, j), other(i, j)) for j in range(self.m)]
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/matrix.py", line 182, in <listcomp>
    entries = [[foo(self(i, j), other(i, j)) for j in range(self.m)]
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/matrix.py", line 182, in <listcomp>
    entries = [[foo(self(i, j), other(i, j)) for j in range(self.m)]
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ops.py", line 122, in imp_foo
    return foo(x, wrap_if_not_expr(y))
  File "/home/lbl/miniconda3/lib/python3.8/site-packages/taichi/lang/ops.py", line 851, in assign
    _ti_core.expr_assign(a.ptr, b.ptr, stack_info())
AttributeError: 'float' object has no attribute 'ptr'

**Comment by bolin12** [comment]
![Screenshot from 2021-11-26 13-43-03](https://user-images.githubusercontent.com/48210500/143533394-498a958d-4512-4b9b-bbfc-82ec331a80b3.png
![Screenshot from 2021-11-26 13-42-53](https://user-images.githubusercontent.com/48210500/143533450-dd6fda17-c34a-4cbe-b0ec-3ae10df56afe.png)
)

**Comment by strongoier** [comment]
The bug should be fixed in #3638 and #3649 now. Could you help verify this after v0.8.7 is released? Thanks!

**Comment by lyd405121** [comment]
I also find my project don't work with 0.8.6 but works well with 0.8.4
- https://github.com/lyd405121/wcsph 
- https://github.com/lyd405121/ti-raytrace

Hope taichi 0.8.7 will solve this~   :)

**Comment by strongoier** [comment]
> I also find my project don't work with 0.8.6 but works well with 0.8.4
> 
>     * https://github.com/lyd405121/wcsph
> 
>     * https://github.com/lyd405121/ti-raytrace
> 
> 
> Hope taichi 0.8.7 will solve this~ :)

It seems that they work fine with current master branch :-)

**Comment by strongoier** [comment]
Hi @bolin12 @lyd405121
Could you help confirm whether v0.8.7 works for you? Thanks!

**Comment by bolin12** [comment]
> 

All fixed. Thanks!

**Comment by lyd405121** [comment]
> Hi @bolin12 @lyd405121 Could you help confirm whether v0.8.7 works for you? Thanks!

Fixed :)
