### ISSUE TITLE
type object 'Expr' has no attribute 'layout_materialized'

### ISSUE THREAD

**Issue by vkurenkov** [taichi-dev/taichi#1335]
**Describe the bug**
The autodiff_minimization.py/autodiff_regression.py examples are not working in 0.6.13 version but working in 0.6.12

**Log/Screenshots**
```
[Taichi] mode=release
[Taichi] version 0.6.13, llvm 10.0.0, commit e8d87357, python 3.7.6
Traceback (most recent call last):
  File "autodiff_minimization.py", line 18, in <module>
    x[i] = random.random()
  File "/home/vkurenkov/.anaconda3/lib/python3.7/site-packages/taichi/lang/util.py", line 212, in wrapped
    return func(*args, **kwargs)
  File "/home/vkurenkov/.anaconda3/lib/python3.7/site-packages/taichi/lang/expr.py", line 39, in __setitem__
    impl.get_runtime().try_materialize()
  File "/home/vkurenkov/.anaconda3/lib/python3.7/site-packages/taichi/lang/impl.py", line 166, in try_materialize
    if not Expr.layout_materialized:
AttributeError: type object 'Expr' has no attribute 'layout_materialized'
```

**To Reproduce**
```
# Install target version
pip install taichi==0.6.13

# Pull the example
git clone https://github.com/taichi-dev/taichi.git
cd taichi/examples/

# Run the example
python autodiff_minimization.py
```

**Comment by yuanming-hu** [comment]
Thanks for reporting. This can be fixed by adding `ti.init()` at the beginning of the example. It's also worth checking if an `ti.init` is missing in any other examples.

If anyone's interested in fixing this, please go ahead and PR. Thanks in advance!
